type t =
  | Null
  | Bool of bool
  | Num of float
  | Str of string
  | List of t list
  | Obj of (string * t) list

exception Bad of string

let fail fmt = Format.kasprintf (fun s -> raise (Bad s)) fmt

(* A small recursive-descent JSON reader. The fixtures are generated by
   conformance/tronweb/generate.mjs and are not adversarial input; this exists
   to keep yojson out of the offline packages' test closure, not to be a
   hardened parser. *)
let parse (s : string) : t =
  let n = String.length s in
  let i = ref 0 in
  let peek () = if !i < n then Some s.[!i] else None in
  let advance () = incr i in
  let rec skip_ws () =
    match peek () with
    | Some (' ' | '\t' | '\n' | '\r') ->
        advance ();
        skip_ws ()
    | _ -> ()
  in
  let expect c =
    skip_ws ();
    match peek () with
    | Some c' when c' = c -> advance ()
    | Some c' -> fail "expected %c, got %c at %d" c c' !i
    | None -> fail "expected %c, got end of input" c
  in
  let literal lit v =
    if !i + String.length lit <= n && String.sub s !i (String.length lit) = lit
    then begin
      i := !i + String.length lit;
      v
    end
    else fail "bad literal at %d" !i
  in
  let string_body () =
    expect '"';
    let b = Buffer.create 32 in
    let rec go () =
      match peek () with
      | None -> fail "unterminated string"
      | Some '"' ->
          advance ();
          Buffer.contents b
      | Some '\\' ->
          advance ();
          (match peek () with
          | Some 'n' ->
              Buffer.add_char b '\n';
              advance ()
          | Some 't' ->
              Buffer.add_char b '\t';
              advance ()
          | Some 'r' ->
              Buffer.add_char b '\r';
              advance ()
          | Some 'b' ->
              Buffer.add_char b '\b';
              advance ()
          | Some 'f' ->
              Buffer.add_char b '\012';
              advance ()
          | Some 'u' ->
              advance ();
              let code = int_of_string ("0x" ^ String.sub s !i 4) in
              i := !i + 4;
              (* The fixtures are ASCII; anything else is a generator bug. *)
              if code < 128 then Buffer.add_char b (Char.chr code)
              else fail "non-ASCII escape \\u%04x" code
          | Some c ->
              Buffer.add_char b c;
              advance ()
          | None -> fail "unterminated escape");
          go ()
      | Some c ->
          Buffer.add_char b c;
          advance ();
          go ()
    in
    go ()
  in
  let number () =
    let start = !i in
    let is_num = function
      | '0' .. '9' | '-' | '+' | '.' | 'e' | 'E' -> true
      | _ -> false
    in
    while match peek () with Some c when is_num c -> true | _ -> false do
      advance ()
    done;
    match float_of_string_opt (String.sub s start (!i - start)) with
    | Some f -> Num f
    | None -> fail "bad number at %d" start
  in
  let rec value () =
    skip_ws ();
    match peek () with
    | Some '"' -> Str (string_body ())
    | Some '{' -> obj ()
    | Some '[' -> arr ()
    | Some 't' -> literal "true" (Bool true)
    | Some 'f' -> literal "false" (Bool false)
    | Some 'n' -> literal "null" Null
    | Some _ -> number ()
    | None -> fail "unexpected end of input"
  and obj () =
    expect '{';
    skip_ws ();
    match peek () with
    | Some '}' ->
        advance ();
        Obj []
    | _ ->
        let acc = ref [] in
        let rec go () =
          skip_ws ();
          let k = string_body () in
          expect ':';
          let v = value () in
          acc := (k, v) :: !acc;
          skip_ws ();
          match peek () with
          | Some ',' ->
              advance ();
              go ()
          | Some '}' ->
              advance ();
              Obj (List.rev !acc)
          | _ -> fail "expected , or } at %d" !i
        in
        go ()
  and arr () =
    expect '[';
    skip_ws ();
    match peek () with
    | Some ']' ->
        advance ();
        List []
    | _ ->
        let acc = ref [] in
        let rec go () =
          let v = value () in
          acc := v :: !acc;
          skip_ws ();
          match peek () with
          | Some ',' ->
              advance ();
              go ()
          | Some ']' ->
              advance ();
              List (List.rev !acc)
          | _ -> fail "expected , or ] at %d" !i
        in
        go ()
  in
  let v = value () in
  skip_ws ();
  if !i <> n then fail "trailing input at %d" !i;
  v

let read_file path =
  let ic = open_in_bin path in
  Fun.protect
    ~finally:(fun () -> close_in ic)
    (fun () -> really_input_string ic (in_channel_length ic))

let load path = parse (read_file path)
let mem t k = match t with Obj kvs -> List.mem_assoc k kvs | _ -> false

let field t k =
  match t with
  | Obj kvs -> (
      match List.assoc_opt k kvs with
      | Some v -> v
      | None -> fail "no field %S" k)
  | _ -> fail "not an object, looking for %S" k

let list = function List l -> l | _ -> fail "not a list"
let str = function Str s -> s | _ -> fail "not a string"

let int = function
  | Num f when Float.is_integer f -> int_of_float f
  | Num f -> fail "not an integer: %f" f
  | _ -> fail "not a number"

let get_str t k = str (field t k)
let get_int t k = int (field t k)
let get_list t k = list (field t k)
let strings t = List.map str (list t)
let find l ~name = List.find (fun t -> String.equal (get_str t "name") name) l
